### ISSUE TITLE
Object is not a function

### ISSUE THREAD

**Issue by argosback** [dominicbarnes/node-constants#3]
when I try to include your module with `var define = require('constants')(exports)`, I get a exception

```
E:\Development\nodejs\node_modules\marval\lib\marval.js:11
var define = require('constants')(exports)
                                  ^
TypeError: object is not a function
    at Object.<anonymous> (E:\Development\nodejs\node_modules\marval\lib\marval.js:11:34)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (E:\Development\nodejs\node_modules\marval\index.js:8:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by dominicbarnes** [comment]
It looks like `constants` is a name that is used by node core, so the returned module is actually an (undocumented) internal module set up for constants... looks like I need to rename my module :(
